name: Deploy Action

on:
  workflow_run:
    workflows: [ "Build and Test Actions" ]
    branches: [ master ]
    types:
      - completed

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download build
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build-test.yml
          workflow_conclusion: success
          name: deploy_dist

      - name: Deploy to Github Pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: micro-time-tracker